#!/bin/bash
# /opt/inventory/deploy.sh
# Usage: deploy.sh <image_tag> <ghcr_prefix> [slack_webhook]
#
# Blue-green deployment for the Inventory app (client + api).
# Ports:
#   Blue  → client:3030, api:3031
#   Green → client:3032, api:3033
# DB is the host Postgres, reached via host.docker.internal (see docker-compose.yml).
set -euo pipefail

IMAGE_TAG=$1
GHCR_PREFIX=$(echo "$2" | tr '[:upper:]' '[:lower:]')
SLACK_WEBHOOK=${3:-""}

DEPLOY_DIR=/opt/inventory
COMPOSE_FILE=$DEPLOY_DIR/docker-compose.yml
STATE_FILE=$DEPLOY_DIR/active-slot
SHA_FILE=$DEPLOY_DIR/stable-sha
NGINX_UPSTREAM=/etc/nginx/conf.d/inventory-upstream.conf

log()  { echo "[$(date '+%H:%M:%S')] $*"; }
fail() { log "ERROR: $*"; exit 1; }

notify() {
  local msg=$1
  log "$msg"
  if [ -n "$SLACK_WEBHOOK" ]; then
    curl -s -X POST "$SLACK_WEBHOOK" -H 'Content-type: application/json' \
      --data "{\"text\":\"$msg\"}" > /dev/null || true
  fi
}

# ── Resolve blue/green ────────────────────────────────────────────────────────
CURRENT_SLOT=$(cat "$STATE_FILE" 2>/dev/null || echo "blue")
STABLE_SHA=$(cat "$SHA_FILE" 2>/dev/null || echo "none")

if [ "$CURRENT_SLOT" = "blue" ]; then
  TARGET_SLOT=green
  CLIENT_PORT=3032; API_PORT=3033
else
  TARGET_SLOT=blue
  CLIENT_PORT=3030; API_PORT=3031
fi

log "Deploying $IMAGE_TAG → $TARGET_SLOT (current: $CURRENT_SLOT/$STABLE_SHA)"
log "  client → :$CLIENT_PORT | api → :$API_PORT"

# ── Pull images ───────────────────────────────────────────────────────────────
log "Pulling images..."
docker pull "$GHCR_PREFIX-client:$IMAGE_TAG" || fail "Failed to pull client image"
docker pull "$GHCR_PREFIX-api:$IMAGE_TAG"    || fail "Failed to pull api image"

# ── Start new stack ───────────────────────────────────────────────────────────
log "Starting $TARGET_SLOT stack..."
export SLOT=$TARGET_SLOT
export CLIENT_PORT API_PORT
export IMAGE_TAG GHCR_PREFIX

docker compose -f "$COMPOSE_FILE" -p "inventory-$TARGET_SLOT" down 2>/dev/null || true
docker compose -f "$COMPOSE_FILE" -p "inventory-$TARGET_SLOT" up -d || fail "docker compose up failed"

log "Stack started — running health checks..."

# ── Health check gate (20 × 3s = 60s) ─────────────────────────────────────────
HEALTHY=false
for i in $(seq 1 20); do
  CLIENT_OK=$(curl -sf -o /dev/null -w "%{http_code}" --max-time 3 "http://localhost:$CLIENT_PORT/" 2>/dev/null || echo "000")
  API_OK=$(curl -sf -o /dev/null -w "%{http_code}" --max-time 3 "http://localhost:$API_PORT/api/health" 2>/dev/null || echo "000")
  log "  Attempt $i/20 — client:$CLIENT_OK api:$API_OK"
  if [ "$CLIENT_OK" = "200" ] && [ "$API_OK" = "200" ]; then
    HEALTHY=true
    log "All health checks passed on attempt $i/20"
    break
  fi
  sleep 3
done

# ── Auto rollback on failure ──────────────────────────────────────────────────
if [ "$HEALTHY" = "false" ]; then
  log "Health check FAILED — container logs:"
  docker compose -f "$COMPOSE_FILE" -p "inventory-$TARGET_SLOT" logs --no-color --tail=50 2>/dev/null || true
  log "Rolling back..."
  docker compose -f "$COMPOSE_FILE" -p "inventory-$TARGET_SLOT" down 2>/dev/null || true
  notify "DEPLOY FAILED inventory ($IMAGE_TAG) — auto-rolled back. Still on: $STABLE_SHA ($CURRENT_SLOT)."
  exit 1
fi

# ── Nginx atomic switch ───────────────────────────────────────────────────────
log "Switching Nginx upstream to $TARGET_SLOT (client:$CLIENT_PORT, api:$API_PORT)"
tee "$NGINX_UPSTREAM" > /dev/null <<UPSTREAM
# Auto-generated by deploy.sh — do not edit manually
# Active slot: $TARGET_SLOT | SHA: $IMAGE_TAG | $(date)

upstream inventory_client {
    server 127.0.0.1:$CLIENT_PORT;
}

upstream inventory_api {
    server 127.0.0.1:$API_PORT;
}
UPSTREAM

nginx -t || fail "Nginx config test failed — not reloading"
systemctl reload nginx
log "Nginx reloaded — traffic now on $TARGET_SLOT"

# ── Stop old stack ────────────────────────────────────────────────────────────
OLD_SLOT=$CURRENT_SLOT
log "Stopping old stack: $OLD_SLOT"
docker compose -f "$COMPOSE_FILE" -p "inventory-$OLD_SLOT" down 2>/dev/null || true

# ── Persist state ─────────────────────────────────────────────────────────────
echo "$TARGET_SLOT" > "$STATE_FILE"
echo "$IMAGE_TAG"   > "$SHA_FILE"

# ── Cleanup old images (keep last 3 per repo) ─────────────────────────────────
for img in "$GHCR_PREFIX-client" "$GHCR_PREFIX-api"; do
  docker images "$img" --format "{{.Repository}}:{{.Tag}} {{.CreatedAt}}" \
    | grep -v "latest" | sort -rk2 | awk '{print $1}' | tail -n +4 \
    | xargs -r docker rmi 2>/dev/null || true
done
docker image prune -f
docker container prune -f

notify "DEPLOY SUCCESS inventory ($IMAGE_TAG) — live on $TARGET_SLOT (client:$CLIENT_PORT api:$API_PORT)"
log "Done."
